version: 0.2

phases:
  install:
    commands:
      - echo "Installing unzip"
      - yum update -y
      - yum install -y unzip
      - "curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
      - "unzip terraform_1.5.7_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - "terraform version"
      - pip install -r requirements.txt



  pre_build:
    commands:
      - echo "Detecting changed jobs for PLAN"
      - |
        CHANGED_JOBS=$(git diff --name-only ${CODEBUILD_RESOLVED_SOURCE_VERSION}^ ${CODEBUILD_RESOLVED_SOURCE_VERSION} \
          | grep "^jobs/" | cut -d "/" -f2 | sort | uniq)
        echo "Changed jobs: $CHANGED_JOBS"

  build:
    commands:
      - echo "Running terraform PLAN in each changed job"
      - |
        for job in $CHANGED_JOBS; do
          if [ -d "jobs/$job" ]; then
            cd jobs/$job
            terraform init -backend-config=codepipeline.tfbackend
            terraform plan -var-file=codepipeline.tfvars -out=tfplan
            cd ../../
          fi
        done

artifacts:
  files:
    - jobs/**/tfplan
