version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - aws --version
      - terraform --version
  build:
    commands:
      - echo "Starting build phase"
      - cd terraform
      - terraform init
      - terraform plan -var-file=codepipeline.tfvars -out=tfplan
      - terraform show -no-color tfplan > tfplan.txt
  post_build:
    commands:
      - echo "Starting post-build phase"
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 0 ]; then exit 1; fi
      - echo "Terraform plan completed successfully"

artifacts:
  files:
    - terraform/tfplan
    - terraform/tfplan.txt
  name: plan-artifact

cache:
  paths:
    - '/root/.terraform.d/plugin-cache/**/*'
