# version: 0.2

# env:
#   variables:
#     TF_PLUGIN_CACHE_DIR: /root/.terraform.d/plugin-cache
#     # Set ARTIFACT_BUCKET in the CodeBuild project / pipeline env
#     # ARTIFACT_BUCKET: my-tf-artifacts-bucket

# phases:
#   install:
#     commands:
#       - yum update -y && yum install -y unzip
#       - curl -sSLO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
#       - unzip -o terraform_1.5.7_linux_amd64.zip && mv terraform /usr/local/bin/
#       - mkdir -p "${TF_PLUGIN_CACHE_DIR}"
#       - terraform version
#       - pip install -r requirements.txt

#   pre_build:
#     commands:
#       - echo "Detecting changed jobs"
#       # - docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
#       - git fetch origin "+refs/heads/*:refs/remotes/origin/*" --depth=50 || true
#       - |
#         if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
#           BASE_COMMIT=$(git rev-parse HEAD^)
#           CHANGED_JOBS=$(git diff --name-only "$BASE_COMMIT" HEAD | grep -E '^jobs/[^/]+/' | cut -d'/' -f2 | sort -u)
#         else
#           CHANGED_JOBS=$(ls -1 jobs || true)
#         fi
#       - echo "CHANGED_JOBS=$CHANGED_JOBS"

#       - echo "Build wheels for changed jobs"
#       - |
#         for job in $CHANGED_JOBS; do
#           [ -d "jobs/$job" ] || continue
#           pushd "jobs/$job" >/dev/null
#           rm -rf ./dist ./utils-0.1-py3-none-any.whl
#           docker build -t glue-job-builder .
#           CID=$(docker create glue-job-builder)
#           docker cp "$CID":/out/utils-0.1-py3-none-any.whl ./utils-0.1-py3-none-any.whl
#           docker rm "$CID"
#           popd >/dev/null
#         done

#   build:
#     commands:
#       - |
#         set -e
#         for job in $CHANGED_JOBS; do
#           [ -d "jobs/$job" ] || continue
#           echo "=== Planning $job ==="
#           terraform -chdir="jobs/$job" fmt -recursive
#           terraform -chdir="jobs/$job" init -input=false -backend-config=terraform.tfbackend
#           terraform -chdir="jobs/$job" validate -no-color
#           # plan; allow detailed exit codes without failing the build
#           if terraform -chdir="jobs/$job" plan -no-color -input=false -var-file=terraform.tfvars -out=tfplan -detailed-exitcode; then
#             :
#           else
#             EXIT=$?; [ "$EXIT" -eq 2 ] || exit "$EXIT"
#           fi
#           terraform -chdir="jobs/$job" show -no-color tfplan > "tfplan.txt" || true
#           terraform -chdir="jobs/$job" show -json tfplan > "tfplan.json" || true
#         done

#   post_build:
#     commands:
#       - |
#         set -e
#         ARTIFACT_BUCKET=${ARTIFACT_BUCKET:?Set ARTIFACT_BUCKET env var}
#         COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION:-manual-$(date +%s)}
#         echo "Uploading plan artifacts to s3://${ARTIFACT_BUCKET}/runs/${COMMIT}/jobs/"
#         aws s3 sync jobs/ "s3://${ARTIFACT_BUCKET}/runs/${COMMIT}/jobs/" \
#           --exclude "*" \
#           --include "*/tfplan" \
#           --include "*/tfplan.txt" \
#           --include "*/tfplan.json" \
#           --include "*/utils-*.whl" \
#           --include "*/requirements.txt"

#         # Write 'latest.txt' without process substitution
#         printf %s "$COMMIT" | aws s3 cp - "s3://${ARTIFACT_BUCKET}/runs/latest.txt" \
#           --content-type text/plain --cache-control no-store
#         echo "Uploaded artifacts for commit ${COMMIT}"

# artifacts:
#   files:
#     - jobs/**/tfplan
#     - jobs/**/tfplan.txt
#     - jobs/**/tfplan.json
#     - jobs/**/utils-0.1-py3-none-any.whl
#     - jobs/**/requirements.txt
#   discard-paths: no

# cache:
#   paths:
#     - /root/.terraform.d/plugin-cache/**



version: 0.2

env:
  variables:
    TF_PLUGIN_CACHE_DIR: /root/.terraform.d/plugin-cache

phases:
  install:
    commands:
      - |
        set -euo pipefail
        yum install -y unzip >/dev/null || (yum update -y && yum install -y unzip)
        curl -sSLO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip -o terraform_1.5.7_linux_amd64.zip && mv terraform /usr/local/bin/
        mkdir -p "${TF_PLUGIN_CACHE_DIR}"
        terraform version

  pre_build:
    commands:
      - |
        set -euo pipefail
        # collect unique Terraform dirs under jobs/ and sp_jobs/
        APPLY_DIRS="$(find jobs sp_jobs -type f -name '*.tf' 2>/dev/null | xargs -r -n1 dirname | sort -u)"
        echo "APPLY_DIRS: ${APPLY_DIRS:-<none>}"
        : > plan_dirs.txt

  build:
    commands:
      - |
        set -euo pipefail
        for dir in ${APPLY_DIRS}; do
          echo "=== Planning in ${dir} ==="
          terraform -chdir="${dir}" fmt -recursive
          terraform -chdir="${dir}" init -input=false -backend-config=terraform.tfbackend
          terraform -chdir="${dir}" validate -no-color
          terraform -chdir="${dir}" plan -input=false -no-color -out=tfplan
          terraform -chdir="${dir}" show -json tfplan > tfplan.json || true
          terraform -chdir="${dir}" show tfplan > tfplan.txt || true
          [ -f "${dir}/.terraform.lock.hcl" ] || { echo "Missing .terraform.lock.hcl in ${dir}"; exit 1; }
          echo "${dir}" >> plan_dirs.txt
        done

  post_build:
    commands:
      - |
        set -euo pipefail
        ARTIFACT_BUCKET=${ARTIFACT_BUCKET:?Set ARTIFACT_BUCKET env var}
        COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION:-manual-$(date +%s)}

        echo "Uploading plan artifacts to s3://${ARTIFACT_BUCKET}/runs/${COMMIT}/"

        # Upload jobs/ (plans + config + lock + glue bits)
        aws s3 sync jobs/ "s3://${ARTIFACT_BUCKET}/runs/${COMMIT}/jobs/" \
          --exclude "*" \
          --include "*/tfplan" \
          --include "*/tfplan.txt" \
          --include "*/tfplan.json" \
          --include "*/terraform.tfbackend" \
          --include "*/.terraform.lock.hcl" \
          --include "*/*.tf" \
          --include "*/requirements.txt" \
          --include "*/utils-*.whl"

        # Upload sp_jobs/ (plans + config + lock)
        aws s3 sync sp_jobs/ "s3://${ARTIFACT_BUCKET}/runs/${COMMIT}/sp_jobs/" \
          --exclude "*" \
          --include "*/tfplan" \
          --include "*/tfplan.txt" \
          --include "*/tfplan.json" \
          --include "*/terraform.tfbackend" \
          --include "*/.terraform.lock.hcl" \
          --include "*/*.tf"

        # Manifest + latest marker
        aws s3 cp plan_dirs.txt "s3://${ARTIFACT_BUCKET}/runs/${COMMIT}/plan_dirs.txt"
        printf %s "$COMMIT" | aws s3 cp - "s3://${ARTIFACT_BUCKET}/runs/latest.txt" --content-type text/plain --cache-control no-store
        echo "Uploaded artifacts for commit ${COMMIT}"
        
artifacts:
  files:
    - plan_dirs.txt
    - jobs/**/tfplan
    - jobs/**/tfplan.txt
    - jobs/**/tfplan.json
    - jobs/**/.terraform.lock.hcl
    - jobs/**/terraform.tfbackend
    - jobs/**/*.tf
    - jobs/**/utils-0.1-py3-none-any.whl
    - jobs/**/requirements.txt
    - sp_jobs/**/tfplan
    - sp_jobs/**/tfplan.txt
    - sp_jobs/**/tfplan.json
    - sp_jobs/**/.terraform.lock.hcl
    - sp_jobs/**/terraform.tfbackend
    - sp_jobs/**/*.tf
  discard-paths: no

cache:
  paths:
    - /root/.terraform.d/plugin-cache/**

