version: 0.2

phases:
  install:
    commands:
      - echo "Installing unzip"
      - yum update -y
      - yum install -y unzip
      - rm -rf terraform
      - "curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
      - "unzip terraform_1.5.7_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - "terraform version"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Detecting changed jobs for APPLY"
      - |
        CHANGED_JOBS=$(ls jobs)  # You may refine this detection based on artifact presence
      - echo "Changed jobs: $CHANGED_JOBS"
  build:
    commands:
      - echo "Running terraform APPLY in each changed job"
      - |
        for job in $CHANGED_JOBS; do
          if [ -f "jobs/$job/tfplan" ]; then
            cd jobs/$job
            terraform init -backend-config=codepipeline.tfbackend
            terraform apply -var-file=codepipeline.tfvars tfplan
            cd ../../
          fi
        done